### ISSUE TITLE
Failed while IPN validation

### ISSUE THREAD

**Issue by ernilambar** [axisthemes/woocommerce-esewa#5]
I am testing plugin in development environment. Redirection is working well. Fund is also deducted but in WooCommerce order status is failed. 
`Payment failed via IPN. Order status changed from Pending Payment to Failed.`

**Comment by shivapoudel** [comment]
@ernilambar can you paste the log data for eSewa gateway :)

**Comment by ernilambar** [comment]
Here is the log.


06-04-2015 @ 03:53:38 - Generating payment form for order 15. Notify URL: http://rabmalin.tk/wc-api/WC_Gateway_eSewa/
06-04-2015 @ 03:53:50 - Checking IPN response is valid
06-04-2015 @ 03:53:50 - IPN Request: Array
(
    [body] => Array
        (
            [amt] => 18.00
            [pid] => WC-15
            [rid] => 0003ZAW
            [scd] => service123
        )

    [timeout] => 60
    [sslverify] => 
    [httpversion] => 1.1
    [compress] => 
    [decompress] => 
    [user-agent] => WooCommerce/2.3.10
)

06-04-2015 @ 03:53:50 - IPN Response: WP_Error Object
(
    [errors] => Array
        (
            [http_request_failed] => Array
                (
                    [0] => couldn't connect to host
                )

        )

    [error_data] => Array
        (
        )

)

06-04-2015 @ 03:53:50 - Received invalid response from eSewa
06-04-2015 @ 03:53:50 - Error response: couldn't connect to host
06-04-2015 @ 03:53:50 - Found order #15
06-04-2015 @ 03:53:50 - Payment status: failed

**Comment by shivapoudel** [comment]
@ernilambar Is this on sandbox mode or live mode xD

**Comment by shivapoudel** [comment]
@ernilambar IMO you might be the victim because of this `'sslverify' => false` try to remove them and test. If it works then let me know else I need test credentials for http://rabmalin.tk/
https://github.com/axisthemes/woocommerce-esewa/search?q=sslverify&type=Code&utf8=%E2%9C%93

**Comment by shivapoudel** [comment]
I have test and couldn't reproduce this bug at http://axisthemes.com/shop/

**Comment by shivapoudel** [comment]
@ernilambar This issue doesn't seem to be related to the WordPress installation generally, but communication between servers. One thing to check is to see if you can determine from your host if the fsockopen php function is enabled. That's used for communication from the plugin to eSewa servers, so if it's disabled that would explain the hold up.

Go to *WooCommerce -> System Status* and check `fsockopen/cURL:` is enable or disable. It really needs to be enable in your server to validate IPN request :)

**Comment by ernilambar** [comment]
May be this is server issue.

`PayPal IPN won't work with your server. Contact your hosting provider. `

Thanks
